# 03 Availability And Next Steps

This is the decision notebook: what we can build now, what is pending, and what the team can review together.

![Data readiness](../reports/figures/data_readiness.svg)

In [1]:
readiness = pd.DataFrame(...)
readiness

         Product layer            Status                                                     Why
            Graph base             Ready                 Parcels, APN, address fields, city/ZIP.
Explainability context             Ready    Zoning, risk, schools, amenities, Census boundaries.
         Permit signal Ready for SF demo 1.29M SF permits; San Ramon feed still needs follow-up.
  Production valuation         Not ready                           Comparable sales are missing.

## Pending Items

In [2]:
blocked = pd.read_csv('../reports/blocked_or_deferred_sources.csv')
blocked

                    source_id                   status                                                                                                                                           reason                                                                                                                         next_step
         county_sales_records                  blocked                                                          No verified free automated bulk comparable-sales source for San Ramon/Contra Costa yet.                                                               Secure permitted comps source or seed 50-200 sale records manually.
            bay_area_511_gtfs            needs_api_key                                                                                               511 GTFS and transit APIs require a 511 API token.                                         Register at 511.org, set TRANSIT_511_API_KEY, then download regional operator_id=RG feed.
geofabrik_california_full_pbf      deferred_large_file                                               Full California OSM PBF is about 1.3 GB. This repo uses an Overpass San Ramon POI extract instead.                Download only if team needs offline OSM processing: https://download.geofabrik.de/north-america/us/california.html
               census_acs_5yr            needs_api_key                                                                          Current Census API requests redirect to missing_key.html without a key.                                   Set CENSUS_API_KEY and pull selected ACS variables for Contra Costa/SF tracts and block groups.
     cde_public_districts_txt manual_download_or_retry The separate district-only endpoint returned an HTML bot-validation page in automated download. The combined schools/districts file is included. Use the included CDE schools/districts file or manually download the district-only extract from the CDE directory page if needed.

## Suggested Owner Split

In [3]:
next_steps = pd.DataFrame(...)
next_steps

      Workstream  Status         Owner need                                                      Next action
Comparable sales Pending       Owner needed    Find legal comps source or manually seed 50-200 sale records.
     511 transit Pending     API key needed              Register for 511 token and pull GTFS regional feed.
   ACS variables Pending     API key needed Pull tract/block-group attributes after Census key is available.
    Parcel joins   Ready   Geospatial owner    Join parcels to city, zoning, risk, schools, Census, and OSM.
  SF permit demo   Ready Data/product owner                   Use as fast ingestion/explanation proof point.

## Decision Point

We can build the knowledge graph and explanation demo now. We should hold production-grade valuation claims until comparable sales are secured.